### ISSUE TITLE
issues in grouping

### ISSUE THREAD

**Issue by wildrakbil** [datavisyn/chartjs-scale-hierarchical#12]
Hello mister Gratzl we find a new issues thank for your time, I hope you have a good day

In the following pdf, there is a replica of the issues
[issues.pdf](https://github.com/datavisyn/chartjs-scale-hierarchical/files/2712537/issues.pdf)

in the following Url he is the pen
https://codepen.io/wildrakbil/pen/MZedyL

**Comment by sgratzl** [comment]
closing for now, if the issue still remains please reopen or create another issue
