### ISSUE TITLE
Combination with pie breaks pie graph

### ISSUE THREAD

**Issue by svenbw** [datavisyn/chartjs-scale-hierarchical#13]
If you use a pie chart and the hierarchical scale plugin on the same page the pie chart will not draw.

This is caused by the `_enabled`  function which checks if the `type` is set to `hierarchical` for the x or y scale. However if there is no scale configured the property will not be found and the script will fail.

The solution is to modify the `_enabled` method to:
```js
_enabled: function _enabled(chart) {
  if (!chart.config.options.hasOwnProperty('scales')) {
    return null;
  }

  if (this._isValidScaleType(chart, 'xAxes') && chart.config.options.scales.xAxes[0].type === 'hierarchical') {
    return 'x';
  }

  if (this._isValidScaleType(chart, 'yAxes') && chart.config.options.scales.yAxes[0].type === 'hierarchical') {
    return 'y';
  }

  return null;
},
```

The first line checks if there is a scale property, the `_isValidScale_type` method will do a full check:
```js
_isValidScaleType: function _isValidScaleType(chart, scale) {
  if (!chart.config.options.scales.hasOwnProperty(scale)) {
    return false;
  }

  if (!Array.isArray(chart.config.options.scales[scale])) {
    return false;
  }

  return chart.config.options.scales[scale][0].hasOwnProperty('type');
},
```

This solves the issue and allows the different chart types on one page.

**Comment by sgratzl** [comment]
can you provide a PR for that, please?
