### ISSUE TITLE
Use of different colors (sequential color schemes depending on p-values) with two dataset does not work in hierarchical view

### ISSUE THREAD

**Issue by StephanDecker** [datavisyn/chartjs-scale-hierarchical#15]
See working example with only one color for two datasets (testdata is also in git):
https://gitlab.bayer.com/Target360/plugins/gtex/blob/develop/src/Mouse2ManBarChart.ts

If you change the 6 arrays in the following code block to [this.blues((<any>this.node2values.get(node)).qval),'green'] it does not work
https://gitlab.bayer.com/Target360/plugins/gtex/blob/5a5bb325ac582a5e095945fcefdbc11a3ff8235b/src/Mouse2ManBarChart.ts#L253-272

See also codepen (it doesn't work in generel - for whatever reason)
https://codepen.io/stephandecker/pen/XLbvNw?editors=0010

**Comment by sluger** [comment]
fixed with https://github.com/datavisyn/chartjs-scale-hierarchical/releases/tag/v1.2.1
