### ISSUE TITLE
How to change padding?

### ISSUE THREAD

**Issue by georgemeng** [datavisyn/chartjs-scale-hierarchical#24]
In this page https://github.com/datavisyn/chartjs-scale-hierarchical, it shows that hierarchy scale axis has style option. How could I change the one option like padding from 25 to 50? 

The reason is that my chart label is long, I have to wrap them but still need change the padding to make space for the x-axis labels.

Thank you very much!

George

**Comment by sgratzl** [comment]
you mean as in https://codepen.io/sgratzl/pen/LYYxeKg?editors=0010

```js
...
options: {
      scales: {
        xAxes: [{
          type: 'hierarchical',          
          padding: 50,
        }]
...
```

**Comment by georgemeng** [comment]
Perfect! I just tested and it is working great! This plugin is so awesome!

Thank you very much for your help!

George
